"""siparise email ve product_id

Revision ID: 31cc9e594695
Revises: 56e177af92b9
Create Date: 2026-07-08 17:33:14.527110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cc9e594695'
down_revision: Union[str, Sequence[str], None] = '56e177af92b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###
