"""operator auth ve oturum tablolari

Revision ID: 630045e45cbb
Revises: f42f3b196a35
Create Date: 2026-09-03 15:12:26.726152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '630045e45cbb'
down_revision: Union[str, Sequence[str], None] = 'f42f3b196a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_sessions_expires_at'), 'operator_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_operator_sessions_token'), 'operator_sessions', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_sessions_token'), table_name='operator_sessions')
    op.drop_index(op.f('ix_operator_sessions_expires_at'), table_name='operator_sessions')
    op.drop_table('operator_sessions')
    op.drop_table('operator_auth')
    # ### end Alembic commands ###
