"""orderitem edited_path

Revision ID: 7193e337229d
Revises: bdb2827cbd3e
Create Date: 2026-07-10 21:21:00.281045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7193e337229d'
down_revision: Union[str, Sequence[str], None] = 'bdb2827cbd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('edited_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'edited_path')
    # ### end Alembic commands ###
