"""kuyruk durumu + artimli centroid

Revision ID: bdb2827cbd3e
Revises: 31cc9e594695
Create Date: 2026-07-10 13:51:41.676392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb2827cbd3e'
down_revision: Union[str, Sequence[str], None] = '31cc9e594695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('centroid', sa.LargeBinary(), nullable=True))
    op.add_column('customers', sa.Column('face_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('photos', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('photos', sa.Column('error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_photos_status'), 'photos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_status'), table_name='photos')
    op.drop_column('photos', 'error')
    op.drop_column('photos', 'status')
    op.drop_column('customers', 'face_count')
    op.drop_column('customers', 'centroid')
    # ### end Alembic commands ###
